MAKEAPPS := rfclient

#The below line enables the FPM connection to Quagga, the include directory 
#needs to point to fpm.h in quagga
#CFLAGS += -DFPM_ENABLED -I../../quagga-fpm/fpm/ 
include ../Make.rules
